@startuml ER3

hide circle
skinparam linetype ortho
skinparam nodesep 100
skinparam ranksep 130

entity "Пользователь" {
  * email
  --
  полное_имя
  телефон
  роль
}

entity "Продавец" {
  * название_компании
  --
  описание
  рейтинг
}

entity "Товар" {
  * название
  --
  описание
  цена
  количество_на_складе
  зарезервировано
  рейтинг
}

entity "Категория" {
  * название
  --
  описание
}

entity "Заказ" {
  * номер_заказа
  --
  статус
  итоговая_сумма
  дата_заказа
}

entity "Позиция заказа" {
  * номер_позиции
  --
  количество
  цена_на_момент_покупки
}

entity "Отзыв" {
  * пользователь
  * товар
  --
  оценка
  комментарий
  дата_отзыва
}

entity "Адрес" {
  * город
  * улица
  * дом
  * индекс
  --
  квартира
  основной_или_нет
}

entity "История цен" {
  * дата_изменения
  --
  старая_цена
  новая_цена
}

' === Связи ===

Пользователь ||--o| Продавец : "имеет профиль"
Пользователь ||--o{ Заказ : "оформляет"
Пользователь ||--o{ Адрес : "имеет"
Пользователь ||--o{ Отзыв : "оставляет"

Продавец ||--o{ Товар : "владеет"
Продавец ||--o{ Заказ : "обрабатывает"

Товар }o--o{ Категория : "относится к"
Товар ||--o{ Отзыв : "написан на"
Товар ||--o{ "История цен" : "имеет"

Категория ||--o{ Категория : "содержит"

Заказ ||--o{ "Позиция заказа" : "содержит"
Заказ }o--o| Адрес : "доставляется на"

"Позиция заказа" }o--|| Товар : "включает"

@enduml
